DECLARE @Table1 TABLE (SSRef VARCHAR(MAX));
DECLARE @Table2 TABLE (SSRef VARCHAR(MAX));

INSERT INTO @Table1 (SSRef) VALUES ('AAA'), ('BBB'), ('DDD'), ('FFF');
INSERT INTO @Table2 (SSRef) VALUES ('AAA'), ('CCC'), ('EEE'), ('FFF');

SELECT 'UNION';
SELECT SSRef FROM @Table1
UNION
SELECT SSRef FROM @Table2
ORDER BY SSRef;

SELECT 'UNION ALL';
SELECT SSRef FROM @Table1
UNION ALL
SELECT SSRef FROM @Table2
ORDER BY SSRef;

SELECT 'INTERSECT';
SELECT SSRef FROM @Table1
INTERSECT
SELECT SSRef FROM @Table2
ORDER BY SSRef;

SELECT 'EXCEPT';
SELECT SSRef FROM @Table1
EXCEPT
SELECT SSRef FROM @Table2
ORDER BY SSRef;




